#provider
region              = "us-east-1"
profile             = "lessonvult"
environment_type    = "Prod"
projectname         = "Lesson"
ec2_instance_type   = "t2.micro"
lesson_number       = "5"
vpc_cidr            = "172.22.0.0/16"
subnet_public_cidr  = "172.22.12.0/26"
subnet_private_cidr = "172.22.22.0/26"
subnet_availib_zone = "us-east-1a"
