#provider
region               = "us-east-1"
profile              = "lessonvult"
environment_type     = "Dev"
projectname          = "Lesson"
ec2_instance_type    = "t2.micro"
lesson_number        = "5"
vpc_cidr             = "172.42.0.0/16"
subnetA_cidr         = "172.42.16.0/26"
subnetB_cidr         = "172.42.26.0/26"
subnetA_availib_zone = "us-east-1a"
subnetB_availib_zone = "us-east-1b"
